Fix X offset not applied on IOS
SrBrahma/react-native-shadow-2 pull request #68
Opened 2023-03-19 13:13 UTC by YoussefHenna

Fix to match usage of 'start' instead of 'left', which apparently caused issue with application of offset on IOS (https://github.com/SrBrahma/react-native-shadow-2/issues/67)

2023-04-04 10:22 UTC, YoussefHenna commented
@SrBrahma You get the chance to review this yet?

2023-04-13 16:32 UTC, algarcia-vector approved these changes

2023-04-13 18:02 UTC, algarcia-vector commented
Yes, I need this fix too :D

2023-04-14 13:42 UTC, tobi110289 commented
Me too, looking forward! Thank you :)

2023-04-14 14:56 UTC, tobi110289 requested changes

2023-04-14 16:12 UTC, merged

2023-04-14 16:23 UTC, SrBrahma commented
Hi, I am sorry for the delay. I have been away from the programming but I am now coming back!

This should be fixed in 7.0.7. Please, do try it!

While I made this change slightly different in the code, I merged this so you show up as a contributor to the repo ;)

2023-04-14 17:10 UTC, tobi110289 commented
Thank you, works flawlessly now!